variables:
- group: API_KEYS

jobs:
  - job: MINGW
    timeoutInMinutes: 360
    pool:
      vmImage: vs2015-win2012r2
    strategy:
      maxParallel: 5
      matrix:
        i686:
          MINGW_UPPER: MINGW32
          MINGW_LOWER: mingw32
          MINGW_ARCH: i686
          HB_COMPILER: mingw
          BINTRAY_ARCH: x86
        x86_64:
          MINGW_UPPER: MINGW64
          MINGW_LOWER: mingw64
          MINGW_ARCH: x86_64
          HB_COMPILER: mingw64 
          BINTRAY_ARCH: x64
    steps:
      - script: |
          git clone https://github.com/lazka/msys2-ci-base.git %CD:~0,2%\msys64
          %CD:~0,2%\msys64\usr\bin\rm -rf %CD:~0,2%\msys64\.git
        displayName: Install MSYS2

      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc "bash upload_bintray.sh"
        displayName: upload ver harbour-windows-$(BINTRAY_ARCH)-$BUILD_BUILDNUMBER  to bintray - ne radi bez CHERE_INVOKING
        env:
          CHERE_INVOKING: yes
          BINTRAY_API_KEY: $(BINTRAY_API_KEY)

      #- task: PublishBuildArtifacts@1
      #  displayName: Publish packages
      #  continueOnError: true
      #  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
      #  inputs:
      #    pathtoPublish: $(Build.SourcesDirectory)/artifacts
      #    artifactName: harbour-$(MINGW_ARCH)